import type { Metadata } from "next";
import Provider from "@/provider/Provider";
import Navbar from "@/components/Organisms/Navbar/Navbar";
import Image from "@/components/Atoms/Image/Image";
import Footer from "@/components/Organisms/Footer/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Music Player",
  description: "Generated by create next app",
  authors: { name: "Mahdi FayyaziMoghaddam" },
  icons: "./svgs/logo.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* React Scan for Debugging on blow */}
        {/* <script
          crossOrigin="anonymous"
          src="//unpkg.com/react-scan/dist/auto.global.js"
        /> */}
      </head>
      <body
        className="Root relative flex flex-col justify-start items-stretch bg-linear-0 from-dark-800 via-dark-500 to-dark-800 text-dark-100 h-screen overflow-hidden scrollbar-hidden"
        cz-shortcut-listen="true"
      >
        <Image
          src="./images/background.png"
          className="bg-transparent -z-10 h-full object-fill opacity-50 shrink-0"
          alt="background"
          style={{
            position: "absolute",
            aspectRatio: "16/1",
          }}
        />
        <Navbar />
        <Provider>{children}</Provider>
        <Footer />
      </body>
    </html>
  );
}
